### ISSUE TITLE
It's normal for image to contain slashes

### ISSUE THREAD

**Issue by Minizinger** [yfoelling/yair#9]
For some reason you don't allow for image with more than single slash https://github.com/yfoelling/yair/blob/b368c6a45dd72cb1a306d90880f480ca4dc2d466/yair.py#L71

Which renders yair unusable for my case with images like `custom-registry.com/group/subgroup/image:tag`  
docker allows for it, why not yair?

**Comment by yfoelling** [comment]
The main problem is, gatering the image namespace of the image specified. But feeld free to provide an PR for this issue.
